#!/usr/bin/env python3
"""
Privacy Monitor — DEAR-Inspired Pipeline
==========================================
Implements a privacy monitoring pipeline inspired by the DEAR framework
(Detect, Evaluate, Act, Report) extended to cover all six data lifecycle
stages: Collection, Storage, Access, Sharing, Retention, Deletion.

Consumes activity log JSON files generated by privacy_fsm_simulation.py
and produces a structured compliance report.

Usage:
    python privacy_monitor.py <activity_log.json> [--output <report.json>]
"""

import json
import sys
import argparse
from datetime import datetime
from typing import Dict, List, Any, Tuple


# ─────────────────────────────────────────────────────────────
#  D — DETECT stage
#  Identify events carrying privacy-relevant signals or flags
# ─────────────────────────────────────────────────────────────

# Known flag → severity mapping
FLAG_SEVERITY: Dict[str, str] = {
    "CONSENT_MISSING":                     "HIGH",
    "SENSITIVE_DATA_UNENCRYPTED":           "CRITICAL",
    "UNAUTHENTICATED_ACCESS":               "CRITICAL",
    "UNLOGGED_ACCESS":                      "HIGH",
    "DPA_MISSING":                          "HIGH",
    "NO_LEGAL_BASIS_FOR_SHARING":           "CRITICAL",
    "CROSS_BORDER_TRANSFER_WITHOUT_DPA":    "HIGH",
    "RETENTION_POLICY_NOT_APPLIED":         "MEDIUM",
    "INSECURE_DELETION":                    "HIGH",
    "DELETION_NOT_AUDITED":                 "MEDIUM",
    "COMPLIANCE_CHECK_FAILED":              "MEDIUM",
}

# Sensitive personal data types — any unprotected handling escalates severity
SENSITIVE_DATA_TYPES = {
    "diagnosis", "prescriptions", "lab_results", "allergies",
    "vaccination_records", "health_data", "special_educational_needs",
    "disciplinary_records", "free_school_meal_eligibility", "safeguarding_notes",
    "credit_card_number", "passport_number", "biometric_data", "genetic_data",
}

def detect(event: dict) -> List[dict]:
    """Return a list of detected privacy signals from the event."""
    detections = []
    flags = event.get("flags", [])

    for flag in flags:
        if flag.startswith("INCIDENT:"):
            incident_type = flag.replace("INCIDENT:", "").lower()
            detections.append({
                "signal_type": "INCIDENT",
                "flag": flag,
                "severity": "CRITICAL",
                "detail": f"Privacy incident detected: {incident_type}",
            })
        elif flag in FLAG_SEVERITY:
            detections.append({
                "signal_type": "POLICY_VIOLATION",
                "flag": flag,
                "severity": FLAG_SEVERITY[flag],
                "detail": f"Flag raised: {flag}",
            })
        else:
            detections.append({
                "signal_type": "UNKNOWN_FLAG",
                "flag": flag,
                "severity": "LOW",
                "detail": f"Unrecognised flag: {flag}",
            })

    # Additional heuristic detections
    data_type = event.get("data_type", "")
    state     = event.get("event_type", "")

    if state == "DATA_SHARING" and data_type in SENSITIVE_DATA_TYPES:
        if not event.get("dpa_in_place"):
            detections.append({
                "recipient": "email_marketing_vendor",
                "recipient_role": "processor",
                "dpa_required": True,
                "dpa_in_place": False,
                "legal_basis_documented": True,
                "signal_type": "SENSITIVE_DATA_SHARING_WITHOUT_DPA",
                "flag": "SENSITIVE_SHARE_NO_DPA",
                "severity": "CRITICAL",
                "detail": f"Sensitive data type '{data_type}' shared without DPA.",
            })

    if state == "DATA_COLLECTION" and not event.get("consent_obtained") and data_type in SENSITIVE_DATA_TYPES:
        detections.append({
            "signal_type": "SENSITIVE_DATA_WITHOUT_CONSENT",
            "flag": "SENSITIVE_COLLECT_NO_CONSENT",
            "severity": "CRITICAL",
            "detail": f"Sensitive data type '{data_type}' collected without consent.",
        })

    if state == "DATA_ACCESS" and event.get("actor_role") in ["housekeeping", "receptionist"]:
        if data_type in SENSITIVE_DATA_TYPES:
            detections.append({
                "signal_type": "UNAUTHORISED_ROLE_ACCESSING_SENSITIVE_DATA",
                "flag": "ROLE_DATA_MISMATCH",
                "severity": "HIGH",
                "detail": f"Role '{event.get('actor_role')}' accessing sensitive data type '{data_type}'.",
            })

    return detections


# ─────────────────────────────────────────────────────────────
#  E — EVALUATE stage
#  Evaluate each detection against policy rules
# ─────────────────────────────────────────────────────────────

# Policy rules: detection_type → (violation_type, recommended_action)
POLICY_RULES = {
    "POLICY_VIOLATION": {
        "CONSENT_MISSING":                   ("consent_violation",        "request_retroactive_consent_or_suppress_data"),
        "SENSITIVE_DATA_UNENCRYPTED":        ("encryption_violation",     "encrypt_data_immediately_and_alert_dpo"),
        "UNAUTHENTICATED_ACCESS":            ("access_control_violation", "revoke_session_and_alert_security_team"),
        "UNLOGGED_ACCESS":                   ("audit_trail_violation",    "retroactively_log_and_investigate"),
        "DPA_MISSING":                       ("legal_violation",          "suspend_sharing_and_obtain_dpa"),
        "NO_LEGAL_BASIS_FOR_SHARING":        ("legal_violation",          "halt_sharing_and_document_legal_basis"),
        "CROSS_BORDER_TRANSFER_WITHOUT_DPA": ("transfer_violation",       "block_transfer_and_notify_dpo"),
        "RETENTION_POLICY_NOT_APPLIED":      ("retention_violation",      "trigger_retention_review"),
        "INSECURE_DELETION":                 ("deletion_violation",       "re_delete_securely_and_audit"),
        "DELETION_NOT_AUDITED":              ("audit_trail_violation",    "add_retroactive_deletion_record"),
        "COMPLIANCE_CHECK_FAILED":           ("compliance_violation",     "escalate_to_compliance_team"),
    }
}

def evaluate(event: dict, detections: List[dict]) -> List[dict]:
    """Return evaluation outcomes for each detection."""
    evaluations = []
    for det in detections:
        sig  = det["signal_type"]
        flag = det["flag"]
        sev  = det["severity"]

        violation_type = "unknown_violation"
        action         = "log_and_investigate"

        if sig == "INCIDENT":
            violation_type = "privacy_incident"
            action         = "initiate_incident_response_procedure"
        elif sig == "POLICY_VIOLATION":
            rule = POLICY_RULES.get("POLICY_VIOLATION", {}).get(flag)
            if rule:
                violation_type, action = rule
        elif sig == "SENSITIVE_DATA_SHARING_WITHOUT_DPA":
            violation_type = "sensitive_data_legal_violation"
            action = "halt_sharing_notify_dpo_obtain_dpa"
        elif sig == "SENSITIVE_DATA_WITHOUT_CONSENT":
            violation_type = "consent_violation"
            action = "suppress_or_delete_data_notify_dpo"
        elif sig == "UNAUTHORISED_ROLE_ACCESSING_SENSITIVE_DATA":
            violation_type = "access_control_violation"
            action = "revoke_access_and_review_rbac"
        elif sig == "UNKNOWN_FLAG":
            violation_type = "unclassified"
            action = "manual_review"

        evaluations.append({
            "signal_type":    sig,
            "flag":           flag,
            "severity":       sev,
            "violation_type": violation_type,
            "recommended_action": action,
            "event_id":       event.get("timestamp"),
            "event_type":     event.get("event_type"),
            "actor":          event.get("actor"),
            "data_type":      event.get("data_type"),
        })
    return evaluations


# ─────────────────────────────────────────────────────────────
#  A — ACT stage
#  Determine and record the action taken for each violation
# ─────────────────────────────────────────────────────────────

ACTION_OUTCOMES = {
    "request_retroactive_consent_or_suppress_data": "DATA_SUPPRESSED",
    "encrypt_data_immediately_and_alert_dpo":        "ALERT_RAISED",
    "revoke_session_and_alert_security_team":        "SESSION_REVOKED",
    "retroactively_log_and_investigate":             "INVESTIGATION_OPENED",
    "suspend_sharing_and_obtain_dpa":                "SHARING_SUSPENDED",
    "halt_sharing_and_document_legal_basis":         "SHARING_HALTED",
    "block_transfer_and_notify_dpo":                 "TRANSFER_BLOCKED",
    "trigger_retention_review":                      "RETENTION_REVIEW_TRIGGERED",
    "re_delete_securely_and_audit":                  "REDELETION_QUEUED",
    "add_retroactive_deletion_record":               "AUDIT_RECORD_ADDED",
    "escalate_to_compliance_team":                   "COMPLIANCE_ESCALATION",
    "initiate_incident_response_procedure":          "INCIDENT_RESPONSE_INITIATED",
    "halt_sharing_notify_dpo_obtain_dpa":            "SHARING_HALTED",
    "suppress_or_delete_data_notify_dpo":            "DATA_SUPPRESSED",
    "revoke_access_and_review_rbac":                 "ACCESS_REVOKED",
    "log_and_investigate":                           "LOGGED",
    "manual_review":                                 "MANUAL_REVIEW_REQUESTED",
}

def act(evaluation: dict) -> dict:
    """
    Simulate the remediation action associated with a finding.

    This function does not modify external systems.
    It records the action that a production enforcement layer
    would be expected to perform.
    """

    recommended_action = evaluation.get(
        "recommended_action",
        "log_and_investigate"
    )

    action_outcome = ACTION_OUTCOMES.get(
        recommended_action,
        "LOGGED"
    )

    return {
        **evaluation,

        "action_mode": "SIMULATED",

        "action_executed": False,

        "recommended_action": recommended_action,

        "simulated_action": action_outcome,

        "actioned_at": evaluation.get(
            "event_timestamp"
        )
    }

def calculate_runtime_metrics(
    all_actions: List[dict],
    total_events: int
) -> dict:

    total_events = max(total_events, 1)

    violation_signal_count = len(all_actions)

    violating_event_ids = {
        action.get("event_id")
        for action in all_actions
        if action.get("event_id") is not None
    }

    violating_event_count = len(
        violating_event_ids
    )

    event_violation_rate = round(
        violating_event_count /
        total_events *
        100,
        1
    )

    event_compliance_rate = round(
        100 -
        event_violation_rate,
        1
    )

    signal_rate = round(
        violation_signal_count /
        total_events *
        100,
        1
    )

    return {
        "total_events": total_events,
        "violation_signal_count":
            violation_signal_count,
        "violating_event_count":
            violating_event_count,
        "event_violation_rate_percent":
            event_violation_rate,
        "event_compliance_rate_percent":
            event_compliance_rate,
        "violation_signal_rate_percent":
            signal_rate
    }
# ─────────────────────────────────────────────────────────────
#  R — REPORT stage
#  Aggregate results and produce compliance report
# ─────────────────────────────────────────────────────────────

def report(use_case: str, all_actions: List[dict], total_events: int) -> dict:
    """Aggregate all actions into a compliance report."""
    sev_counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    violation_types: Dict[str, int] = {}
    action_counts: Dict[str, int] = {}
    lifecycle_issues: Dict[str, int] = {}

    for a in all_actions:
        sev = a.get("severity", "LOW")
        sev_counts[sev] = sev_counts.get(sev, 0) + 1
        vt = a.get("violation_type", "unknown")
        violation_types[vt] = violation_types.get(vt, 0) + 1
        at = a.get("simulated_action", "LOGGED")
        action_counts[at] = action_counts.get(at, 0) + 1
        et = a.get("event_type", "UNKNOWN")
        lifecycle_issues[et] = lifecycle_issues.get(et, 0) + 1

    violation_signal_count  = len(all_actions)
   
    if sev_counts["CRITICAL"] > 0:
        overall_posture = "CRITICAL"
    elif sev_counts["HIGH"] > 2:
        overall_posture = "WEAK"
    elif sev_counts["HIGH"] > 0 or sev_counts["MEDIUM"] > 3:
        overall_posture = "MODERATE"
    else:
        overall_posture = "STRONG"
    metrics = calculate_runtime_metrics(
        all_actions,
        total_events
    )
    compliance_rate = metrics[
        "event_compliance_rate_percent"
    ]
    return {
        "report_id": f"MON-{use_case.upper()}-{datetime.now().strftime('%Y%m%d%H%M%S')}",
        "use_case": use_case,
        "generated_at": datetime.now().isoformat(),
        "total_events_processed": total_events,
        "violation_signal_count": metrics["violation_signal_count"],
        "violating_event_count": metrics["violating_event_count"],
        "event_violation_rate_percent": metrics["event_violation_rate_percent"],
        "event_compliance_rate_percent": metrics["event_compliance_rate_percent"],
        "violation_signal_rate_percent": metrics["violation_signal_rate_percent"],
        "compliance_rate_percent": compliance_rate,
        "overall_posture": overall_posture,
        "severity_breakdown": sev_counts,
        "violation_types": violation_types,
        "action_summary": action_counts,
        "lifecycle_issues_by_stage": lifecycle_issues,
        "findings": all_actions,
    }


# ─────────────────────────────────────────────────────────────
#  Pipeline runner
# ─────────────────────────────────────────────────────────────

def run_pipeline(log_data: dict) -> dict:
    all_actions = []
    events = log_data.get("events", [])

    for event in events:
        detections  = detect(event)
        if not detections:
            continue
        evaluations = evaluate(event, detections)
        for ev in evaluations:
            action = act(ev)
            all_actions.append(action)

    return report(log_data.get("use_case", "UNKNOWN"), all_actions, len(events))


def main():
    parser = argparse.ArgumentParser(description="Privacy Monitor — DEAR Pipeline")
    parser.add_argument("log_file", help="Path to activity log JSON file")
    parser.add_argument("--output", default=None)
    args = parser.parse_args()

    with open(args.log_file) as f:
        log_data = json.load(f)

    rep = run_pipeline(log_data)

    print(f"\n{'='*60}")
    print(f"  Privacy Monitor Report — {rep['use_case']}")
    print(f"{'='*60}")
    print(f"  Events processed : {rep['total_events_processed']}")
    print(f"  Violations found : {rep['violation_signal_count _detected']}")
    print(f"  Compliance rate  : {rep['compliance_rate_percent']}%")
    print(f"  Posture          : {rep['overall_posture']}")
    print(f"  Severity         : {rep['severity_breakdown']}")
    print(f"  Lifecycle issues : {rep['lifecycle_issues_by_stage']}")
    print(f"{'='*60}\n")

    out_path = args.output or args.log_file.replace("_activity_log.json", "_monitor_report.json")
    with open(out_path, "w") as f:
        json.dump(rep, f, indent=2)
    print(f"Monitor report saved to: {out_path}")


if __name__ == "__main__":
    main()
